# Generated by Django 4.0.3 on 2022-05-30 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('friendly_name', models.CharField(max_length=128)),
                ('code_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4)),
                ('modified_by', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('friendly_name', models.CharField(max_length=128)),
                ('code_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(default=uuid.uuid4)),
                ('modified_by', models.UUIDField(default=uuid.uuid4)),
                ('permisions', models.ManyToManyField(related_name='roles', to='Permissions.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
