# Generated by Django 4.0.3 on 2022-06-10 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='created_by',
            field=models.UUIDField(verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='permission',
            name='modified_by',
            field=models.UUIDField(null=True, verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.UUIDField(verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='role',
            name='modified_by',
            field=models.UUIDField(null=True, verbose_name=uuid.uuid4),
        ),
    ]
