# Generated by Django 4.0.3 on 2022-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permissions', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='users', to='Permissions.role'),
        ),
    ]
