# Generated by Django 4.0.3 on 2022-06-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_rename_role_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
