# Generated by Django 4.0.3 on 2022-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenKeys', '0002_alter_authenkey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenkey',
            name='token_key',
            field=models.CharField(max_length=256),
        ),
    ]
