# Generated by Django 4.0.3 on 2022-06-10 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='created_by',
            field=models.UUIDField(verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='modified_by',
            field=models.UUIDField(verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
