# Generated by Django 4.0.3 on 2022-06-10 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracking', '0002_alter_timetracking_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracking',
            name='created_by',
            field=models.UUIDField(null=True, verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='modified_by',
            field=models.UUIDField(null=True, verbose_name=uuid.uuid4),
        ),
    ]
